In [18]:
pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.10/dist-packages (3.4.1)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)

In [19]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('practise').getOrCreate()

In [44]:
df_pyspark=spark.read.csv('data2.csv', header=True, inferSchema=True)

In [21]:
##drop the column
df_pyspark.drop("Name").show()

+----+----------+------+
| age|experience|salary|
+----+----------+------+
|  21|         5| 10000|
|  21|         5| 20000|
|  25|        10| 30000|
|  42|        23| 40000|
|  36|        14| 50000|
|  36|        12| 60000|
|null|      null| 70000|
|  50|        10|  8000|
|  45|      null|  null|
+----+----------+------+

In [22]:
df_pyspark.show()

+-------+----+----------+------+
|   Name| age|experience|salary|
+-------+----+----------+------+
| roheth|  21|         5| 10000|
|roshaan|  21|         5| 20000|
|   banu|  25|        10| 30000|
|  dhoni|  42|        23| 40000|
|  virat|  36|        14| 50000|
|  raina|  36|        12| 60000|
|  ajith|null|      null| 70000|
|   null|  50|        10|  8000|
|   null|  45|      null|  null|
+-------+----+----------+------+

In [23]:
## removing null values
df_pyspark.na.drop().show()

+-------+---+----------+------+
|   Name|age|experience|salary|
+-------+---+----------+------+
| roheth| 21|         5| 10000|
|roshaan| 21|         5| 20000|
|   banu| 25|        10| 30000|
|  dhoni| 42|        23| 40000|
|  virat| 36|        14| 50000|
|  raina| 36|        12| 60000|
+-------+---+----------+------+

In [24]:
df_pyspark.na.drop(how="all").show()
# the row get dropped if all coumn has null value

+-------+----+----------+------+
|   Name| age|experience|salary|
+-------+----+----------+------+
| roheth|  21|         5| 10000|
|roshaan|  21|         5| 20000|
|   banu|  25|        10| 30000|
|  dhoni|  42|        23| 40000|
|  virat|  36|        14| 50000|
|  raina|  36|        12| 60000|
|  ajith|null|      null| 70000|
|   null|  50|        10|  8000|
|   null|  45|      null|  null|
+-------+----+----------+------+

In [25]:
df_pyspark.na.drop(how="any").show()

+-------+---+----------+------+
|   Name|age|experience|salary|
+-------+---+----------+------+
| roheth| 21|         5| 10000|
|roshaan| 21|         5| 20000|
|   banu| 25|        10| 30000|
|  dhoni| 42|        23| 40000|
|  virat| 36|        14| 50000|
|  raina| 36|        12| 60000|
+-------+---+----------+------+

In [26]:
df_pyspark.na.drop(how="any", thresh=2).show()
# minimum 2 null values must be present

+-------+----+----------+------+
|   Name| age|experience|salary|
+-------+----+----------+------+
| roheth|  21|         5| 10000|
|roshaan|  21|         5| 20000|
|   banu|  25|        10| 30000|
|  dhoni|  42|        23| 40000|
|  virat|  36|        14| 50000|
|  raina|  36|        12| 60000|
|  ajith|null|      null| 70000|
|   null|  50|        10|  8000|
+-------+----+----------+------+

In [27]:
df_pyspark.na.drop(how="any", subset=['age']).show()
#null value in particular cloumn

+-------+---+----------+------+
|   Name|age|experience|salary|
+-------+---+----------+------+
| roheth| 21|         5| 10000|
|roshaan| 21|         5| 20000|
|   banu| 25|        10| 30000|
|  dhoni| 42|        23| 40000|
|  virat| 36|        14| 50000|
|  raina| 36|        12| 60000|
|   null| 50|        10|  8000|
|   null| 45|      null|  null|
+-------+---+----------+------+

In [57]:
###filling the missing the value
df_pyspark.na.fill(value=0).show()

+-------+---+----------+------+
|   Name|age|experience|salary|
+-------+---+----------+------+
| roheth| 21|         5| 10000|
|roshaan| 21|         5| 20000|
|   banu| 25|        10| 30000|
|  dhoni| 42|        23| 40000|
|  virat| 36|        14| 50000|
|  raina| 36|        12| 60000|
|  ajith|  0|         0| 70000|
|   null| 50|        10|  8000|
|   null| 45|         0|     0|
+-------+---+----------+------+

In [56]:
df_pyspark.na.fill(0,['experience', 'age']).show()

+-------+---+----------+------+
|   Name|age|experience|salary|
+-------+---+----------+------+
| roheth| 21|         5| 10000|
|roshaan| 21|         5| 20000|
|   banu| 25|        10| 30000|
|  dhoni| 42|        23| 40000|
|  virat| 36|        14| 50000|
|  raina| 36|        12| 60000|
|  ajith|  0|         0| 70000|
|   null| 50|        10|  8000|
|   null| 45|         0|  null|
+-------+---+----------+------+

In [58]:
df_pyspark.show()

+-------+----+----------+------+
|   Name| age|experience|salary|
+-------+----+----------+------+
| roheth|  21|         5| 10000|
|roshaan|  21|         5| 20000|
|   banu|  25|        10| 30000|
|  dhoni|  42|        23| 40000|
|  virat|  36|        14| 50000|
|  raina|  36|        12| 60000|
|  ajith|null|      null| 70000|
|   null|  50|        10|  8000|
|   null|  45|      null|  null|
+-------+----+----------+------+

In [60]:
from pyspark.ml.feature import Imputer

imputer = Imputer(
    inputCols=['age', 'experience', 'salary'],
    outputCols=["{}_imputed".format(c) for c in ['age', 'experience', 'salary']]
).setStrategy("mean") #median #mode

In [61]:
#add imputation cols to df
imputer.fit(df_pyspark).transform(df_pyspark).show()

+-------+----+----------+------+-----------+------------------+--------------+
|   Name| age|experience|salary|age_imputed|experience_imputed|salary_imputed|
+-------+----+----------+------+-----------+------------------+--------------+
| roheth|  21|         5| 10000|         21|                 5|         10000|
|roshaan|  21|         5| 20000|         21|                 5|         20000|
|   banu|  25|        10| 30000|         25|                10|         30000|
|  dhoni|  42|        23| 40000|         42|                23|         40000|
|  virat|  36|        14| 50000|         36|                14|         50000|
|  raina|  36|        12| 60000|         36|                12|         60000|
|  ajith|null|      null| 70000|         34|                11|         70000|
|   null|  50|        10|  8000|         50|                10|          8000|
|   null|  45|      null|  null|         45|                11|         36000|
+-------+----+----------+------+-----------+------------------+--------------+